include $(UPCPP_ROOT)/include/upcxx.mak

PROJECT_CXXFLAGS= -O3 $(UPCXX_CXXFLAGS) -I$(HABANERO_UPC_ROOT)/include -DDIST_WS -I$(HCPP_ROOT)/include -I$(LIBXML2_INCLUDE) -DHUPCPP -DHCPP_COMM_WORKER 
PROJECT_LDFLAGS = $(LDFLAGS) $(UPCXX_LDFLAGS) -L$(HCPP_ROOT)/lib -L$(LIBXML2_LIBS)
PROJECT_LDLIBS = -lhcpp -lxml2 $(HABANERO_UPC_ROOT)/lib/libhcupcpp.a $(UPCXX_LDLIBS)

ifdef TBB_MALLOC
  PROJECT_LDFLAGS += -L$(TBB_MALLOC)
  PROJECT_LDLIBS += -ltbbmalloc_proxy
endif 
