include $(UPCPP_INSTALL)/include/upcxx.mak

PROJECT_CXXFLAGS=$(UPCXX_CXXFLAGS) -I$(HCLIB_ROOT)/include -I$(HABANERO_UPC_INSTALL)/include
PROJECT_LDFLAGS=$(LDFLAGS) $(UPCXX_LDFLAGS) -L$(HCLIB_ROOT)/lib -L$(OCR_INSTALL)/lib  -L$(HABANERO_UPC_INSTALL)/lib
PROJECT_LDLIBS=$(UPCXX_LDLIBS) -lhclib -locr -lhcupcpp

